FROM python:3.11-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster_dbt \
    dbt-duckdb

# Set $DAGSTER_HOME and copy dagster instance there
ENV DAGSTER_HOME=/opt/dagster/dagster_home
ENV DAGSTER_DBT_PARSE_PROJECT_ON_LOAD=1

RUN mkdir -p $DAGSTER_HOME
COPY dagster.yaml $DAGSTER_HOME

# Add repository code
WORKDIR /opt/dagster/app
# COPY src/ ./

# Run dagster gRPC server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "src/repo.py"]